/**
* @File Name : NHS_FormSupport_Tests.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : September 26, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 26, 2025 |   | Initial Version
**/

public class NHS_FormSupport_Tests {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}