public with sharing class ViewingOffersController {

    // @AuraEnabled(cacheable=true)
    // public static List<Viewings_Offer__c> getInitialData( string availabiltyId) {
    //     return [SELECT Id, Agent__c, Date_of_Viewing__c, Buying_Position__c, Feedback__c, Feedback_Chased__c, Offer__c, New_Offer__c, Notes_Updates__c, Viewer_Name__c FROM Viewings_Offer__c where Availability_Report__c =:availabiltyId];
    // }

   // @AuraEnabled
    //public static void saveRecords(List<Viewings_Offer__c> records) {
     //   upsert records;
    //}
    
}